name: begulas_express
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  provider: ^6.0.5
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  flutter_localizations:
    sdk: flutter
  rename_app: ^1.6.5
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/icons/icons8-zalo-100.png
    - lib/assets/icons/united-states.png
    - lib/assets/icons/vietnam.png
    - lib/assets/icons/LOGO BELUGA FINAL.png

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/OutsideLogo.jpg"
  adaptive_icon_background: "#ffffff"   # dùng cho Android 12+
  adaptive_icon_foreground: "lib/assets/icons/OutsideLogo.jpg"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icons/OutsideLogo.jpg"
  min_sdk_android: 21


# Cấu hình l10n: phải cùng cấp với flutter, không thụt vào
l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
  preferred-supported-locales:
    - en
    - vi
