name: begulas_express
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  shared_preferences: ^2.5.3
  intl: ^0.18.1
  provider: ^6.0.5
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/icons8-zalo-100.png
